// Generated by CoffeeScript 1.7.1
(function() {
  define(function() {
    var fieldsConfig;
    return fieldsConfig = {
      "default": {
        RequestedBy: {
          title: 'Requested By',
          autofocus: true
        },
        Name: {
          title: 'Request Title'
        },
        Description: {
          title: 'Request Description (Project & Why needed)',
          type: 'TextArea',
          optional: true
        },
        Priority: {
          title: 'Priority',
          type: 'Select',
          assetName: 'RequestPriority'
        }
      }
    };
  });

}).call(this);
