// Generated by CoffeeScript 1.3.3
(function() {

  define(['./fields'], function(fields) {
    var assetName, host, options, projectName, service, serviceGateway, showDebugMessages, versionOneAuth;
    showDebugMessages = true;
    host = "https://www12.v1host.com";
    service = "https://www12.v1host.com/ProofpointAPITest/rest-1.v1/Data/";
    versionOneAuth = "bstussy:Proofpoint!";
    serviceGateway = false;
    projectName = "'System (All Projects)'";
    assetName = "Request";
    options = {
      showDebug: showDebugMessages,
      projectName: projectName,
      host: host,
      service: service,
      serviceGateway: serviceGateway,
      versionOneAuth: versionOneAuth,
      assetName: assetName,
      formFields: fields
    };
    return options;
  });

}).call(this);
